## ROOT_IDX: 153
## F1_i_child IDX: 154 
## F1_o_child IDX:

- 153
    - ~153 154
        - ~153~154 163
        - ~153!154 20
    - !153 40
        - !153~40 55
        - !153!40 260
    

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
from multiprocessing import Pool, cpu_count
import sys
from collections import Counter
import pickle
path = sys.argv[1]
chunksize = sys.argv[2]
dfs = pd.read_csv(path, chunksize = chunksize)
start_time = datetime.now()
res = Counter()
for i, df in enumerate(dfs):
    running_time = datetime.now()
    print("completed:", round(i*chunksize/120e4,4), '%', 'estimated remaining:', 
          (running_time-start_time)/((i + 1)*chunksize) * 120e6 - (running_time-start_time))
    true_idx = [i.split() for i in df.Fingerprint.values ]
    true_idx = [i for o in true_idx for i in o]
    c = Counter(true_idx)
    res += c
    
    
with open('root_counter.pickle', 'wb') as handle:
    pickle.dump(res, handle, protocol=pickle.HIGHEST_PROTOCOL)


In [107]:
with open(f'{condition}.pickle', 'wb') as handle:
    pickle.dump(res, handle, protocol=pickle.HIGHEST_PROTOCOL)


In [59]:
m.update('1'.encode('utf8'))
m.hexdigest()

'2ea6201a068c5fa0eea5d81a3863321a87f8d533'

In [ ]:
m.hashvalues = m.hashvalues.astype(np.int32)

In [60]:
'1'.encode('utf8')

b'1'

In [64]:
fingerprints = np.zeros(300)

In [67]:
fingerprints[random.sample(range(300),20)] = 1

In [69]:
fingerprints.astype(bool)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,

In [81]:
temp['num_records']/2

15549910.0

In [63]:
print()

1
2
4
6
7
10


In [61]:
chunksize = 10000

In [104]:
def check_in_condition(conds, values):
    res = True
    for cond in conds:
        res &= (cond in values)
    return res

def check_not_in_condition(conds, values):
    res = True
    for cond in conds:
        res &= (cond not in values)
    return res

In [105]:
res = Counter()
condition = 'f1~150~24~17!15!14~13'
must_have = re.findall(r'~(\d+)', condition)
not_have = re.findall(r'!(\d+)', condition)

df = pd.read_csv("./test_shrink_data.csv")
running_time = datetime.now()
print("completed:", round(i*chunksize/120e4,4), '%', 'estimated remaining:', 
      (running_time-start_time)/((i + 1)*chunksize) * 120e6 - (running_time-start_time))
true_idx = [i.split() for i in df.Fingerprint.values ]
true_idx = [i for o in true_idx if (check_in_condition(must_have,o) & check_not_in_condition(not_have,o)) for i in o]
c = Counter(true_idx)
res += c




completed: 0.075 % estimated remaining: 119 days, 11:22:30.685747


In [84]:
import pandas as pd
df = pd.read_csv('./test_shrink_data.csv')

In [86]:
df.Fingerprint.str.split().apply(lambda x: '259' in x)

0         True
1        False
2        False
3         True
4        False
5         True
6         True
7         True
8         True
9        False
10       False
11        True
12        True
13       False
14       False
15        True
16       False
17        True
18       False
19       False
20       False
21       False
22        True
23        True
24        True
25       False
26       False
27        True
28       False
29        True
         ...  
99968    False
99969    False
99970     True
99971    False
99972    False
99973     True
99974    False
99975    False
99976     True
99977     True
99978     True
99979    False
99980    False
99981     True
99982    False
99983    False
99984     True
99985     True
99986     True
99987    False
99988    False
99989    False
99990     True
99991    False
99992    False
99993    False
99994     True
99995     True
99996     True
99997     True
Name: Fingerprint, Length: 99998, dtype: bool

In [92]:
text = a

In [93]:
import re

In [94]:
pattern = r'!(\d+)'

In [96]:
not_have = re.findall(pattern, text)

In [97]:
not_have

['15', '14']

Counter({'0': 88849,
         '3': 97459,
         '4': 96129,
         '7': 95809,
         '9': 86079,
         '10': 97579,
         '11': 75179,
         '12': 81839,
         '13': 82019,
         '15': 82989,
         '18': 51660,
         '19': 45480,
         '23': 65129,
         '24': 86099,
         '27': 74429,
         '31': 86709,
         '35': 97149,
         '36': 90279,
         '38': 59770,
         '39': 46140,
         '40': 40210,
         '41': 70589,
         '43': 65400,
         '45': 71899,
         '46': 82349,
         '47': 77149,
         '48': 92109,
         '50': 52120,
         '51': 87069,
         '55': 55889,
         '56': 79069,
         '58': 55500,
         '59': 42319,
         '60': 97589,
         '61': 63380,
         '66': 85759,
         '67': 69729,
         '69': 60560,
         '71': 83249,
         '72': 75510,
         '73': 87919,
         '75': 72910,
         '76': 86489,
         '77': 68979,
         '79': 62559,
         '81': 

In [1]:
import pickle
with open('fingerprints.pickle', 'rb') as handle:
    temp = pickle.load(handle)

    

In [5]:
type(temp)

numpy.ndarray

In [2]:
temp

{'0': 55379058,
 '3': 60292863,
 '4': 59284977,
 '7': 59371138,
 '9': 53710365,
 '10': 60089522,
 '11': 50446461,
 '12': 51538185,
 '13': 54398216,
 '15': 51516336,
 '18': 36530495,
 '19': 22825285,
 '23': 36337903,
 '24': 54392589,
 '27': 45198855,
 '31': 53889427,
 '35': 59471390,
 '36': 55525348,
 '38': 44389952,
 '39': 26182427,
 '40': 19595140,
 '41': 38997817,
 '43': 37193689,
 '45': 46215049,
 '46': 49477603,
 '47': 46651333,
 '48': 58170478,
 '50': 29568944,
 '51': 54110815,
 '55': 36444376,
 '56': 47769398,
 '58': 42802294,
 '59': 24059192,
 '60': 60386449,
 '61': 34524327,
 '66': 50328923,
 '67': 39024087,
 '69': 36156688,
 '71': 50968654,
 '72': 47210298,
 '73': 53192934,
 '75': 40158836,
 '76': 50940248,
 '77': 38795984,
 '79': 36294476,
 '81': 40821861,
 '84': 40893892,
 '86': 51401879,
 '90': 18576683,
 '91': 50720829,
 '93': 30190127,
 '95': 23319269,
 '96': 51952599,
 '97': 26350105,
 '100': 53890153,
 '101': 33922789,
 '102': 44438063,
 '103': 41651948,
 '104': 5471196

In [111]:
num_records = 123868050

In [4]:
import numpy as np

In [8]:
fingerprints = np.random.randint(0,2 ,(10,5))

In [13]:
import random

In [15]:
random.sample()

TypeError: choice() takes 2 positional arguments but 3 were given

In [18]:
pair = random.sample(range(fingerprints.shape[0]),2)

In [21]:
pair

[5, 4]

In [22]:
fingerprints

array([[0, 0, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1]])

In [33]:
from hashlib import sha1

In [35]:
m = sha1()

In [38]:
m.update(b'1')

b'1'

In [41]:
m.hexdigest()

'356a192b7913b04c54574d18c28d46e6395428ab'

In [25]:
li = [1,2,4,6,7,10]

In [32]:
np.array(li).byteswap()

array([ 72057594037927936, 144115188075855872, 288230376151711744,
       432345564227567616, 504403158265495552, 720575940379279360])

['154',
 '236',
 '158',
 '37',
 '246',
 '52',
 '133',
 '281',
 '93',
 '92',
 '2',
 '260',
 '118',
 '210',
 '44',
 '161',
 '169',
 '259',
 '262',
 '50',
 '20',
 '157',
 '141',
 '107',
 '257',
 '224',
 '148',
 '198',
 '129',
 '179',
 '249',
 '127',
 '200',
 '134',
 '101',
 '267',
 '287',
 '275',
 '280',
 '196',
 '189',
 '61',
 '290',
 '5',
 '89',
 '199',
 '261',
 '186',
 '292',
 '176',
 '183',
 '226',
 '277',
 '163',
 '195',
 '217',
 '184',
 '114',
 '121',
 '97',
 '65',
 '146',
 '240',
 '39',
 '201',
 '124',
 '172',
 '78',
 '28',
 '193',
 '254',
 '160',
 '69',
 '177',
 '79',
 '23',
 '137',
 '273',
 '55',
 '18',
 '174',
 '204',
 '125',
 '215',
 '135',
 '264',
 '82',
 '269',
 '43',
 '117',
 '120',
 '110',
 '228',
 '166',
 '80',
 '59',
 '122',
 '251',
 '274',
 '282',
 '98',
 '63',
 '164',
 '95',
 '54',
 '298',
 '227',
 '77',
 '41',
 '67',
 '19',
 '221',
 '68',
 '142',
 '266',
 '109',
 '33',
 '284',
 '205',
 '211',
 '123',
 '136',
 '145',
 '219',
 '99',
 '170',
 '75',
 '87',
 '233',
 '49',
 